name: macOS build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
#        swift: [ "5.10", "6.0" ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: swift-actions/setup-swift@v2
      if: ${{ false }}
      with:
        swift-version: ${{ matrix.swift }}

    - name: Homebrew Mac
      if: ${{ runner.os == 'Macos' }}
      run: |
        echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
        echo BENCHMARK_DISABLE_JEMALLOC=true >> $GITHUB_ENV
        brew install jemalloc

    - uses: actions/checkout@v4

    - name: GH auth
      run: |
        echo "machine api.github.com login ${{ secrets.GITHUB_TOKEN }} password x-oauth-basic" > $HOME/.netrc
        cat ~/.netrc

    - name: Swift version
      run: swift --version

    - name: Build
      run: swift build

    - name: Run tests
      run: |
        [ -d Tests ] && swift test --parallel

    - name: Run tests (release)
      run: |
        [ -d Tests ] && swift test -c release --parallel
